ALTER TABLE email
DROP COLUMN email_status,
DROP COLUMN sent;

ALTER TABLE email
ADD COLUMN email_status CHARACTER VARYING(255) NOT NULL DEFAULT 'SENT',
ADD COLUMN mandrill_email_status CHARACTER VARYING(255);