ALTER TABLE email
ADD COLUMN discriminator_email_type CHARACTER VARYING(255) NOT NULL DEFAULT 'EMAIL_WITH_TOKEN',
ADD COLUMN subject CHARACTER VARYING(255),
ADD COLUMN message CHARACTER VARYING(255),
ALTER COLUMN token DROP NOT NULL,
ALTER COLUMN token_validated DROP NOT NULL;