# Spring Specific Configuration
spring:
    # Application Contexts to Load.
    applicationContext: ['classpath:applicationContext.xml']

    # Should Spring Security be used?
    useSpringSecurity: false

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: postgres

  # the password
  password: postgres

  # the JDBC URL
  url: jdbc:postgresql://localhost/postgres

server:
  applicationConnectors:
    - type: http
      port: 8085