# Spring Specific Configuration
spring:
    # Application Contexts to Load.
    applicationContext: ['classpath:applicationContext__application__test.xml']

    # Should Spring Security be used?
    useSpringSecurity: false

server:
  applicationConnectors:
    - type: http
      port: 8888