# Spring Specific Configuration
spring:
    # Application Contexts to Load.
    applicationContext: ['classpath:applicationContext.xml']

    # Should Spring Security be used?
    useSpringSecurity: false

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: zkzcxbcanbniah

  # the password
  password: 2TlxpA4GN9KjbNBKqp3oGPVNdK

  # the JDBC URL
  url: jdbc:postgresql://ec2-107-20-177-12.compute-1.amazonaws.com:5432/d5f4hkgdk13f3q

server:
  applicationConnectors:
    - type: http
      port: 8085
    - http:
      - contextParameters:
        - contextConfigLocation: classpath:net/bull/javamelody/monitoring-spring.xml classpath:context/services.xml classpath:context/data-access-layer.xml /WEB-INF/applicationContext.xml