# Spring Specific Configuration
spring:
    # Application Contexts to Load.
    applicationContext: ['classpath:applicationContext.xml']

    # Should Spring Security be used?
    useSpringSecurity: false

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: mupunvxddwtgii

  # the password
  password: b5NYM_0CPuqCYNn-gpDQOl19P3

  # the JDBC URL
  url: jdbc:postgresql://ec2-54-163-250-41.compute-1.amazonaws.com:5432/d4dk6sd7oqlh0m

server:
  applicationConnectors:
    - type: http
      port: 8085