# Spring Specific Configuration
spring:
    # Application Contexts to Load.
    applicationContext: ['classpath:applicationContext.xml']

    # Should Spring Security be used?
    useSpringSecurity: false

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: knfphzceylicyu

  # the password
  password: D1L1oOoVn3UH5PFOxxGPG7BxCJ

  # the JDBC URL
  url: jdbc:postgresql://ec2-54-163-228-188.compute-1.amazonaws.com:5432/ddtkj537nf2gog?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory

server:
  applicationConnectors:
    - type: http
      port: 8085